import{a as v,S as _,i as n}from"./assets/vendor-bPTf7fF8.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const S="https://pixabay.com/api/",q="54667544-34f53a0b28c965f6e0120a2cf";async function d(r,t=1){const s={key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};try{return(await v.get(S,{params:s})).data}catch(a){throw console.error("Info about error",a),a}}const g=document.querySelector(".gallery"),f=document.querySelector(".loader"),y=document.querySelector(".btn"),P=new _(".gallery a",{nav:!0,close:!0,captions:!0,captionsData:"alt",captionDelay:250});async function m(r){const t=r.map(({comments:s,downloads:a,likes:e,views:o,tags:c,webformatURL:L,largeImageURL:w})=>`
     <div class="gallery__card">
        <a href="${w}" class="gallery__image-link">
          <img src="${L}" alt="${c}" loading="lazy" class="gallery__image"/>
        </a>
        <div class="gallery__info">
          <p><b>Likes:</b> ${e}</p>
          <p><b>Views:</b> ${o}</p>
          <p><b>Comments:</b> ${s}</p>
          <p><b>Downloads:</b> ${a}</p>
        </div>
      </div>
     `).join("");g.insertAdjacentHTML("beforeend",t),P.refresh()}function B(){g.innerHTML="",console.log("Галерею очищенно")}function p(){f.classList.add("is-open"),console.log("Завантаження")}function h(){f.classList.remove("is-open"),console.log("Закінчення завантаження")}function b(){y.classList.add("is-open")}function u(){y.classList.remove("is-open")}const $=document.querySelector(".form"),E=document.querySelector(".btn");let l="",i=1;$.addEventListener("submit",async r=>{if(r.preventDefault(),l=r.currentTarget.elements["search-text"].value.trim(),!l){n.warning({message:"Search field cannot be empty!"});return}i=1,B(),u(),p();try{const t=await d(l,i);if(t.hits.length===0)n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});else{m(t.hits);const s=Math.ceil(t.totalHits/15);i<s?b():n.info({message:"We're sorry, but you've reached the end of search results."})}}catch(t){console.log(t),n.error({message:"Something went wrong. Please try again."})}finally{h(),r.target.reset()}});E.addEventListener("click",async()=>{u(),p(),i+=1;try{const r=await d(l,i);m(r.hits);const s=document.querySelector(".gallery__card").getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"});const a=Math.ceil(r.totalHits/15);i>=a?(u(),n.info({message:"We're sorry, but you've reached the end of search results."})):b()}catch(r){n.error({message:"Error fetching images!"}),console.log(r)}finally{h()}});
//# sourceMappingURL=index.js.map
