import{a as w,S as v,i as n}from"./assets/vendor-bPTf7fF8.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const _="https://pixabay.com/api/",S="54667544-34f53a0b28c965f6e0120a2cf";async function g(r,t=1){const s={key:S,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};try{return(await w.get(_,{params:s})).data}catch(a){throw console.error("Info about error",a),a}}const f=document.querySelector(".gallery"),y=document.querySelector(".loader"),m=document.querySelector(".btn"),q=new v(".gallery a",{nav:!0,close:!0,captions:!0,captionsData:"alt",captionDelay:250});async function p(r){const t=r.map(({comments:s,downloads:a,likes:e,views:o,tags:c,webformatURL:b,largeImageURL:L})=>`
     <div class="gallery__card">
        <a href="${L}" class="gallery__image-link">
          <img src="${b}" alt="${c}" loading="lazy" class="gallery__image"/>
        </a>
        <div class="gallery__info">
          <p><b>Likes:</b> ${e}</p>
          <p><b>Views:</b> ${o}</p>
          <p><b>Comments:</b> ${s}</p>
          <p><b>Downloads:</b> ${a}</p>
        </div>
      </div>
     `).join("");f.insertAdjacentHTML("beforeend",t),q.refresh()}function P(){f.innerHTML="",console.log("Галерею очищенно")}function B(){y.classList.add("is-open"),console.log("Завантаження")}function h(){y.classList.remove("is-open"),console.log("Закінчення завантаження")}function u(){m.classList.add("is-open")}function d(){m.classList.remove("is-open")}const $=document.querySelector(".form"),E=document.querySelector(".btn");let l="",i=1;$.addEventListener("submit",async r=>{if(r.preventDefault(),l=r.currentTarget.elements["search-text"].value.trim(),!l){n.warning({message:"Search field cannot be empty!"});return}i=1,P(),d(),u();try{const t=await g(l,i);if(t.hits.length===0)n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});else{p(t.hits);const s=Math.ceil(t.totalHits/15);i<s?u():n.info({message:"We're sorry, but you've reached the end of search results."})}}catch(t){console.log(t),n.error({message:"Something went wrong. Please try again."})}finally{h(),r.target.reset()}});E.addEventListener("click",async()=>{d(),B(),i+=1;try{const r=await g(l,i);p(r.hits);const s=document.querySelector(".gallery__card").getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"});const a=Math.ceil(r.totalHits/15);i>=a?(d(),n.info({message:"We're sorry, but you've reached the end of search results."})):u()}catch(r){n.error({message:"Error fetching images!"}),console.log(r)}finally{h()}});
//# sourceMappingURL=index.js.map
